"""create group expenses and expense splits tables

Revision ID: 44bd838742c6
Revises: 4429d33a2575
Create Date: 2026-09-29 14:06:34.085199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44bd838742c6'
down_revision: Union[str, Sequence[str], None] = '4429d33a2575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('paid_by_member_id', sa.Integer(), nullable=False),
    sa.Column('created_by_member_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('split_method', sa.Enum('equal', 'exact', 'percentage', 'shares', 'adjustment', 'reimbursement', 'itemized', name='splitmethod', native_enum=False, length=20), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_group_expenses_amount_positive')),
    sa.ForeignKeyConstraint(['created_by_member_id'], ['group_members.id'], name=op.f('fk_group_expenses_created_by_member_id_group_members')),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_group_expenses_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paid_by_member_id'], ['group_members.id'], name=op.f('fk_group_expenses_paid_by_member_id_group_members')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_expenses'))
    )
    op.create_index(op.f('ix_group_expenses_created_by_member_id'), 'group_expenses', ['created_by_member_id'], unique=False)
    op.create_index(op.f('ix_group_expenses_group_id'), 'group_expenses', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_expenses_paid_by_member_id'), 'group_expenses', ['paid_by_member_id'], unique=False)
    op.create_table('expense_splits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_expense_splits_amount_positive')),
    sa.ForeignKeyConstraint(['expense_id'], ['group_expenses.id'], name=op.f('fk_expense_splits_expense_id_group_expenses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['group_members.id'], name=op.f('fk_expense_splits_member_id_group_members')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expense_splits')),
    sa.UniqueConstraint('expense_id', 'member_id', name='uq_expense_splits_expense_id_member_id')
    )
    op.create_index(op.f('ix_expense_splits_expense_id'), 'expense_splits', ['expense_id'], unique=False)
    op.create_index(op.f('ix_expense_splits_member_id'), 'expense_splits', ['member_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expense_splits_member_id'), table_name='expense_splits')
    op.drop_index(op.f('ix_expense_splits_expense_id'), table_name='expense_splits')
    op.drop_table('expense_splits')
    op.drop_index(op.f('ix_group_expenses_paid_by_member_id'), table_name='group_expenses')
    op.drop_index(op.f('ix_group_expenses_group_id'), table_name='group_expenses')
    op.drop_index(op.f('ix_group_expenses_created_by_member_id'), table_name='group_expenses')
    op.drop_table('group_expenses')
    # ### end Alembic commands ###
