"""create categories table with system defaults

Revision ID: 6b69150b449a
Revises: 3417caf85c98
Create Date: 2026-09-29 13:18:17.839081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b69150b449a'
down_revision: Union[str, Sequence[str], None] = '3417caf85c98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('income', 'expense', name='categorytype', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_categories_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('user_id', 'name', name='uq_categories_user_id_name')
    )
    op.create_index(op.f('ix_categories_user_id'), 'categories', ['user_id'], unique=False)
    # ### end Alembic commands ###

    categories = sa.table(
        "categories",
        sa.column("name", sa.String),
        sa.column("type", sa.String),
    )
    op.bulk_insert(
        categories,
        [
            {"name": "Food", "type": "expense"},
            {"name": "Shopping", "type": "expense"},
            {"name": "Transport", "type": "expense"},
            {"name": "Education", "type": "expense"},
            {"name": "Entertainment", "type": "expense"},
            {"name": "Bills", "type": "expense"},
            {"name": "Health", "type": "expense"},
            {"name": "Travel", "type": "expense"},
            {"name": "Other", "type": "expense"},
            {"name": "Salary", "type": "income"},
            {"name": "Other Income", "type": "income"},
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_user_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
