"""add username to users

Revision ID: 7fe70c778bf2
Revises: a5de3252c88d
Create Date: 2026-10-02 18:12:43.305822

"""
import re
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fe70c778bf2'
down_revision: Union[str, Sequence[str], None] = 'a5de3252c88d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _handle_from_email(email: str) -> str:
    # A frozen copy of user_service.suggest_username's rule (migrations never import app code).
    base = re.sub(r"[^a-z0-9_]", "", email.split("@")[0].lower())
    if not base[:1].isalpha():
        base = f"user{base}"
    base = base[:26]
    if len(base) < 3:
        base = f"{base}_user"
    return base


def upgrade() -> None:
    """Upgrade schema."""
    # Existing users need a handle before the column can be NOT NULL: add it nullable,
    # backfill from each email (oldest account wins a clash), then tighten.
    op.add_column('users', sa.Column('username', sa.String(length=30), nullable=True))
    conn = op.get_bind()
    taken: set[str] = set()
    for user_id, email in conn.execute(sa.text("SELECT id, email FROM users ORDER BY id")):
        base = _handle_from_email(email)
        candidate, n = base, 1
        while candidate in taken:
            n += 1
            candidate = f"{base}{n}"
        taken.add(candidate)
        conn.execute(sa.text("UPDATE users SET username = :u WHERE id = :id"), {"u": candidate, "id": user_id})
    op.alter_column('users', 'username', nullable=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
