"""create settlements table

Revision ID: a5747c7cc1ca
Revises: 44bd838742c6
Create Date: 2026-09-29 15:00:40.494197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5747c7cc1ca'
down_revision: Union[str, Sequence[str], None] = '44bd838742c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('from_member_id', sa.Integer(), nullable=False),
    sa.Column('to_member_id', sa.Integer(), nullable=False),
    sa.Column('created_by_member_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('settled_on', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_settlements_amount_positive')),
    sa.CheckConstraint('from_member_id <> to_member_id', name=op.f('ck_settlements_different_members')),
    sa.ForeignKeyConstraint(['created_by_member_id'], ['group_members.id'], name=op.f('fk_settlements_created_by_member_id_group_members')),
    sa.ForeignKeyConstraint(['from_member_id'], ['group_members.id'], name=op.f('fk_settlements_from_member_id_group_members')),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_settlements_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_member_id'], ['group_members.id'], name=op.f('fk_settlements_to_member_id_group_members')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settlements'))
    )
    op.create_index(op.f('ix_settlements_from_member_id'), 'settlements', ['from_member_id'], unique=False)
    op.create_index(op.f('ix_settlements_group_id'), 'settlements', ['group_id'], unique=False)
    op.create_index(op.f('ix_settlements_to_member_id'), 'settlements', ['to_member_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settlements_to_member_id'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_group_id'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_from_member_id'), table_name='settlements')
    op.drop_table('settlements')
    # ### end Alembic commands ###
