"""add simplify_debts to groups

Revision ID: d90a4209d24d
Revises: 7fe70c778bf2
Create Date: 2026-10-02 18:23:11.392788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd90a4209d24d'
down_revision: Union[str, Sequence[str], None] = '7fe70c778bf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('simplify_debts', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'simplify_debts')
    # ### end Alembic commands ###
